version: "3.9"

services:
  ui:
    container_name: react_frontend
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/ui/src:/app/src
    environment:
      - WATCHPACK_POLLING=true

networks:
  internal:
    name: internal